# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Frappant\FrpFormAnswers\:
    resource: '../Classes/*'

  Frappant\FrpFormAnswers\Utility\FormAnswersUtility:
    public: true
